name: Env vars

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Env vars
      shell: pwsh
      env:
        IS_FREE_LOCAL: ${{ secrets.IS_FREE }}
      run: |
          [bool]$env:IS_FREE_LOCAL
          [bool]$env:IS_FREE
          if (Test-Path env:IS_FREE_LOCAL) {
            Write-Host "if1"
          }
          ./vars.ps1
